// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrestamoDispositivos.DataContext.Sections;

#nullable disable

namespace PrestamoDispositivos.Migrations
{
    [DbContext(typeof(DatacontextPres))]
    [Migration("20251127163146_actualizacionModeloDEvicemanager")]
    partial class actualizacionModeloDEvicemanager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrestamoDispositivos.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TwoFactorCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Device", b =>
                {
                    b.Property<Guid>("IdDisp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Almacenamiento")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("EstadoDisp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procesador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarjetaGrafica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDisp");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Loan", b =>
                {
                    b.Property<Guid>("IdPrestamos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoPrestamo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdAdminDev")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDispo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEstudiante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEvento")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPrestamos");

                    b.HasIndex("IdAdminDev");

                    b.HasIndex("IdDispo");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdEvento");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.LoanEvent", b =>
                {
                    b.Property<Guid>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoPrestamos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEvento");

                    b.ToTable("EventoPrestamos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Student", b =>
                {
                    b.Property<Guid>("IdEst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Carnet")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<Guid?>("EstadoEstId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("semestreCursado")
                        .HasColumnType("int");

                    b.HasKey("IdEst");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.HasIndex("EstadoEstId");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.deviceManager", b =>
                {
                    b.Property<Guid>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdmin");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("AdminDisp");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.studentStatus", b =>
                {
                    b.Property<Guid>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstEstu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatus");

                    b.ToTable("EstadoEstudiantes");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.ApplicationUser", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Loan", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.deviceManager", "DeviceManager")
                        .WithMany("Loans")
                        .HasForeignKey("IdAdminDev");

                    b.HasOne("PrestamoDispositivos.Models.Device", "Dispositivo")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdDispo");

                    b.HasOne("PrestamoDispositivos.Models.Student", "Estudiante")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrestamoDispositivos.Models.LoanEvent", "EventoPrestamos")
                        .WithMany("EventosPrestamos")
                        .HasForeignKey("IdEvento");

                    b.Navigation("DeviceManager");

                    b.Navigation("Dispositivo");

                    b.Navigation("Estudiante");

                    b.Navigation("EventoPrestamos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Student", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("PrestamoDispositivos.Models.Student", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrestamoDispositivos.Models.studentStatus", "EstadoEst")
                        .WithMany("studentsStu")
                        .HasForeignKey("EstadoEstId");

                    b.Navigation("EstadoEst");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.deviceManager", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Device", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.LoanEvent", b =>
                {
                    b.Navigation("EventosPrestamos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Student", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.deviceManager", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.studentStatus", b =>
                {
                    b.Navigation("studentsStu");
                });
#pragma warning restore 612, 618
        }
    }
}
