// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrestamoDispositivos.DataContext.Sections;

#nullable disable

namespace PrestamoDispositivos.Migrations
{
    [DbContext(typeof(DatacontextPres))]
    partial class DatacontextPresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserAuditReportsClass", b =>
                {
                    b.Property<Guid>("ReporAuditIdAudit")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportUsidUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReporAuditIdAudit", "ReportUsidUsuario");

                    b.HasIndex("ReportUsidUsuario");

                    b.ToTable("UserAuditReports", (string)null);
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Administrator", b =>
                {
                    b.Property<Guid>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroCelular")
                        .HasColumnType("int");

                    b.HasKey("IdAdmin");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorreoElectrónico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RolUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codigo2FA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("idSuperior")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUsuario");

                    b.HasIndex("RolUser");

                    b.HasIndex("idSuperior");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.AuditReportsClass", b =>
                {
                    b.Property<Guid?>("IdAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEvento")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAudit");

                    b.ToTable("ReportesyAuditorias");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Device", b =>
                {
                    b.Property<Guid>("IdDisp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Especificaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdDisp");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Loan", b =>
                {
                    b.Property<Guid>("IdPrestamos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoPrestamo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdDispo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPrestamos");

                    b.HasIndex("IdDispo");

                    b.HasIndex("IdUser");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Request", b =>
                {
                    b.Property<Guid>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("idUser");

                    b.ToTable("solicitud");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Student", b =>
                {
                    b.Property<Guid>("IdEst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentoID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("carnet")
                        .HasColumnType("int");

                    b.Property<int>("numeroCelular")
                        .HasColumnType("int");

                    b.HasKey("IdEst");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.lender", b =>
                {
                    b.Property<Guid>("idPres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("numeroCelular")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("idPres");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("Prestamista");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.setRol", b =>
                {
                    b.Property<Guid>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permisos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("ApplicationUserAuditReportsClass", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.AuditReportsClass", null)
                        .WithMany()
                        .HasForeignKey("ReporAuditIdAudit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReportUsidUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Administrator", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "User")
                        .WithOne("AdminUsuario")
                        .HasForeignKey("PrestamoDispositivos.Models.Administrator", "ApplicationUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.ApplicationUser", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.setRol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolUser")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "Superior")
                        .WithMany()
                        .HasForeignKey("idSuperior");

                    b.Navigation("Rol");

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Loan", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.Device", "Dispositivo")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdDispo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "User")
                        .WithMany("PrestamosUser")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dispositivo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Request", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "User")
                        .WithMany("Solicitudes")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Student", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "User")
                        .WithOne("studentUsuario")
                        .HasForeignKey("PrestamoDispositivos.Models.Student", "ApplicationUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.lender", b =>
                {
                    b.HasOne("PrestamoDispositivos.Models.ApplicationUser", "User")
                        .WithOne("LenderUsuario")
                        .HasForeignKey("PrestamoDispositivos.Models.lender", "ApplicationUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.ApplicationUser", b =>
                {
                    b.Navigation("AdminUsuario");

                    b.Navigation("LenderUsuario");

                    b.Navigation("PrestamosUser");

                    b.Navigation("Solicitudes");

                    b.Navigation("studentUsuario");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.Device", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("PrestamoDispositivos.Models.setRol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
